#!/bin/bash
# =============================================================================
# eBill — Auto Memory Configuration
# =============================================================================
# Detects total system RAM and writes percentage-based memory limits to .env
# Re-run this after any VPS RAM upgrade: make auto-config
#
# Usage:
#   bash scripts/auto-config.sh          # from project root
#   make auto-config                      # via Makefile
# =============================================================================

set -euo pipefail

APP_DIR="${APP_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd .. && pwd)}"
ENV_FILE="${APP_DIR}/.env"

# ── RAM detection ─────────────────────────────────────────────────────────────
TOTAL_RAM_MB=$(free -m | awk '/^Mem:/{print $2}')

echo ""
echo "=== eBill Auto Memory Configuration ==="
echo "Detected RAM: ${TOTAL_RAM_MB}MB total"
echo ""

# ── Percentage allocations ────────────────────────────────────────────────────
# Total container allocation: 76% of RAM (leaves 24% for OS + Docker overhead)
# Increase percentages if you have dedicated server (no other workloads)
MONGO_PCT=30       # MongoDB: largest consumer (data cache)
BACKEND_PCT=25     # FastAPI + Python runtime
FRONTEND_PCT=15    # node + serve static files
CADDY_PCT=6        # Caddy reverse proxy
WATCHTOWER_PCT=3   # Watchtower auto-updater
INIT_PCT=1         # init-env container (runs once and exits)

# ── Calculate limits ──────────────────────────────────────────────────────────
MONGO_LIMIT_MB=$(( TOTAL_RAM_MB * MONGO_PCT / 100 ))
BACKEND_LIMIT_MB=$(( TOTAL_RAM_MB * BACKEND_PCT / 100 ))
FRONTEND_LIMIT_MB=$(( TOTAL_RAM_MB * FRONTEND_PCT / 100 ))
CADDY_LIMIT_MB=$(( TOTAL_RAM_MB * CADDY_PCT / 100 ))
WATCHTOWER_LIMIT_MB=$(( TOTAL_RAM_MB * WATCHTOWER_PCT / 100 ))

# Reservations = 50% of limit (guaranteed minimum)
MONGO_RES_MB=$(( MONGO_LIMIT_MB / 2 ))
BACKEND_RES_MB=$(( BACKEND_LIMIT_MB / 2 ))
FRONTEND_RES_MB=$(( FRONTEND_LIMIT_MB / 2 ))
CADDY_RES_MB=$(( CADDY_LIMIT_MB / 2 ))

# MongoDB WiredTiger cache: 15% of total RAM (expressed in GB for mongod flag)
# Formula: total_mb * 0.15 / 1024  → result in GB with 2 decimal places
MONGO_CACHE_GB=$(awk "BEGIN {printf \"%.2f\", $TOTAL_RAM_MB * 0.15 / 1024}")

# ── Display summary ───────────────────────────────────────────────────────────
echo "Memory allocations (${TOTAL_RAM_MB}MB total):"
printf "  %-12s %4dMB  (%d%%)\n" "MongoDB:"   "$MONGO_LIMIT_MB"    "$MONGO_PCT"
printf "  %-12s %4dMB  (%d%%)\n" "Backend:"   "$BACKEND_LIMIT_MB"  "$BACKEND_PCT"
printf "  %-12s %4dMB  (%d%%)\n" "Frontend:"  "$FRONTEND_LIMIT_MB" "$FRONTEND_PCT"
printf "  %-12s %4dMB  (%d%%)\n" "Caddy:"     "$CADDY_LIMIT_MB"    "$CADDY_PCT"
printf "  %-12s %4dMB  (%d%%)\n" "Watchtower:" "$WATCHTOWER_LIMIT_MB" "$WATCHTOWER_PCT"
TOTAL_ALLOC=$(( MONGO_LIMIT_MB + BACKEND_LIMIT_MB + FRONTEND_LIMIT_MB + CADDY_LIMIT_MB + WATCHTOWER_LIMIT_MB ))
OS_RESERVE=$(( TOTAL_RAM_MB - TOTAL_ALLOC ))
printf "  %-12s %4dMB  (OS + Docker overhead)\n" "Reserved:" "$OS_RESERVE"
echo "  MongoDB WiredTiger cache: ${MONGO_CACHE_GB}GB (15% of RAM)"
echo ""

# ── Write to .env ─────────────────────────────────────────────────────────────
# Remove any previously auto-generated block from .env
if [ -f "$ENV_FILE" ]; then
    # Delete lines between start and end markers (inclusive)
    sed -i '/^# ── AUTO-GENERATED MEMORY LIMITS/,/^# ── END AUTO-GENERATED/d' "$ENV_FILE"
    # Remove trailing blank lines at end of file
    sed -i -e '/^[[:space:]]*$/{/^[[:space:]]*$/!b;N;/^[[:space:]]*$/D}' "$ENV_FILE" 2>/dev/null || true
fi

# Append new auto-generated block
cat >> "$ENV_FILE" << ENVBLOCK

# ── AUTO-GENERATED MEMORY LIMITS ───────────────────────────────────────────────
# Generated by: make auto-config  |  Source RAM: ${TOTAL_RAM_MB}MB
# Re-run after VPS RAM upgrade:   make auto-config && make deploy-ghcr
#
# Percentages: MongoDB ${MONGO_PCT}% | Backend ${BACKEND_PCT}% | Frontend ${FRONTEND_PCT}% | Caddy ${CADDY_PCT}% | Watchtower ${WATCHTOWER_PCT}%
# To adjust ratios, edit scripts/auto-config.sh and re-run make auto-config

MONGO_MEMORY_LIMIT=${MONGO_LIMIT_MB}m
MONGO_MEMORY_RESERVATION=${MONGO_RES_MB}m
MONGO_CACHE_GB=${MONGO_CACHE_GB}

BACKEND_MEMORY_LIMIT=${BACKEND_LIMIT_MB}m
BACKEND_MEMORY_RESERVATION=${BACKEND_RES_MB}m

FRONTEND_MEMORY_LIMIT=${FRONTEND_LIMIT_MB}m
FRONTEND_MEMORY_RESERVATION=${FRONTEND_RES_MB}m

CADDY_MEMORY_LIMIT=${CADDY_LIMIT_MB}m
CADDY_MEMORY_RESERVATION=${CADDY_RES_MB}m

WATCHTOWER_MEMORY_LIMIT=${WATCHTOWER_LIMIT_MB}m
# ── END AUTO-GENERATED ────────────────────────────────────────────────────────
ENVBLOCK

echo "✅ .env updated with memory limits"
echo "   Run 'make deploy-ghcr' or 'make up' to apply changes"
echo ""
